package com.modih.mail.ui.screens.docs

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavController
import com.modih.mail.ui.components.GlassCard
import com.modih.mail.ui.theme.*

@Composable
fun PrivacyPolicyScreen(navController: NavController) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(BgPrimary)
            .verticalScroll(rememberScrollState())
            .statusBarsPadding()
            .padding(horizontal = 20.dp)
    ) {
        Row(
            modifier = Modifier.fillMaxWidth().padding(vertical = 12.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            IconButton(onClick = { navController.popBackStack() }) {
                Icon(Icons.AutoMirrored.Filled.ArrowBack, "Back", tint = TextPrimary)
            }
            Text("Back", fontSize = 14.sp, color = TextMuted)
        }

        GlassCard(modifier = Modifier.fillMaxWidth()) {
            Text(
                "Privacy Policy",
                fontFamily = CormorantGaramond, fontWeight = FontWeight.SemiBold,
                fontStyle = FontStyle.Italic, fontSize = 32.sp, color = AccentGold
            )
            Spacer(Modifier.height(4.dp))
            Text("Last Updated: March 2026", fontSize = 12.sp, color = TextDim, letterSpacing = 1.sp)

            Spacer(Modifier.height(24.dp))

            LegalText("At Modih Mail, your privacy is our primary focus. We provide secure, disposable email services designed to protect your personal information from spam, tracking, and unwanted communications.")

            LegalHeader("1. Information We Collect")
            LegalText("Modih Mail is built to minimize data collection. The information we process includes:")
            LegalBullet("Account Data: If you sign up for a Free or Pro account, we securely store your registration email address and password hash (via Firebase Authentication).")
            LegalBullet("Generated Inboxes: Email prefixes generated by you remain in our system only as long as they are active (up to 7 days for Pro, typically 3 hours for Free).")
            LegalBullet("Email Contents: Emails received by your disposable Modih Mail addresses are stored temporarily so you can read them. They are automatically and permanently deleted from our servers as soon as your inbox expires.")
            LegalBullet("Log Data: We may collect temporary aggregated connection logs for security (e.g., rate limiting and DoS prevention) via our infrastructure providers (Cloudflare).")

            LegalHeader("2. How We Use Your Data")
            LegalText("We use the minimal data collected strictly to operate the service. We do not sell, rent, or trade your data to third parties.")
            LegalBullet("Deliver incoming emails to your generated inboxes.")
            LegalBullet("Manage and authenticate your user account and subscriptions.")
            LegalBullet("Prevent abuse of our systems using Cloudflare Turnstile verification.")

            LegalHeader("3. Data Deletion and Expiry")
            LegalText("Disposable email is ephemeral by design. All incoming messages and temporary inboxes are permanently wiped from our databases immediately upon their expiry time. We keep zero archives or backups of expired disposable emails.")

            LegalHeader("4. Third-Party Services")
            LegalText("Modih utilizes industry-leading infrastructure to ensure security and reliability:")
            LegalBullet("Cloudflare: For DNS, DDoS protection, edge caching, and D1 database hosting.")
            LegalBullet("Firebase (Google): For secure user authentication and account management.")

            LegalHeader("5. Your Rights")
            LegalText("You have the right to delete your Modih Mail account at any time. Doing so will immediately remove your account information and any active disposable inboxes associated with it from our active databases.")

            LegalHeader("6. Changes to this Policy")
            LegalText("We may update this Privacy Policy as our services evolve. If we make significant changes, we will notify registered users via their primary account email.")

            LegalHeader("Contact Us")
            LegalText("If you have any privacy-related questions or concerns, please contact us at privacy@modih.in.")
        }

        Spacer(Modifier.height(40.dp))
    }
}

@Composable
fun LegalHeader(text: String) {
    Spacer(Modifier.height(20.dp))
    Text(
        text,
        fontFamily = CormorantGaramond, fontWeight = FontWeight.SemiBold,
        fontStyle = FontStyle.Italic, fontSize = 22.sp, color = TextPrimary
    )
    Spacer(Modifier.height(8.dp))
}

@Composable
fun LegalText(text: String) {
    Text(
        text,
        fontSize = 14.sp, color = TextSecondary, lineHeight = 22.sp,
        fontFamily = Inter
    )
    Spacer(Modifier.height(8.dp))
}

@Composable
fun LegalBullet(text: String) {
    Row(modifier = Modifier.padding(start = 8.dp, bottom = 6.dp)) {
        Text("•  ", color = AccentGold, fontSize = 14.sp)
        Text(text, fontSize = 14.sp, color = TextSecondary, lineHeight = 20.sp, fontFamily = Inter)
    }
}
